server:
  port: 8080

spring:
  application:
    name: demo

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_TABLE}
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

social:
  google:
    authorization-uri: https://accounts.google.com/o/oauth2/auth
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    user-name-attribute: id
  kakao:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    user-name-attribute: id
  naver:
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    user-name-attribute: response

jwt:
  access-token-time: 9999999  #3600 # 60 * 60 1시간
  refresh-token-time: 9999999  #604800 # 60 * 60 * 24 * 7 1주일